### ISSUE TITLE
Can you please publish your packages to nuget?

### ISSUE THREAD

**Issue by LSTANCZYK** [Pathoschild/FluentJira#2]
Great job!
Exactly what i was looking for. I am intending to use it with my csscript mercurial and git hooks!

I would appreciate if you could publish your packages to nuget!

**Comment by Pathoschild** [comment]
Hi! This is an early experiment — it's not updated with the latest API changes and it doesn't cover the full API yet. There are a few other API clients for C# that might be more complete already, like [farmas' Atlassian.Net SDK](https://bitbucket.org/farmas/atlassian.net-sdk/wiki/Home) and [techtalk's JiraRestClient](https://github.com/techtalk/JiraRestClient) (both on NuGet already).

If those aren't sufficient and there isn't already a good C# client for JIRA, I can definitely resume work to finish it.

**Comment by Pathoschild** [comment]
I did a bit more work on this and published a [prerelease NuGet package](https://www.nuget.org/packages/Pathoschild.FluentJira/0.0.1-alpha). I'm using it in a few small projects, but I'm only actively using a few parts of the API (mainly issues and versions).

**Comment by Pathoschild** [comment]
@LSTANCZYK I did a bit more work on this and published a prerelease NuGet package. I'm using it in a few small projects, but I'm only actively using a few parts of the API (mainly issues and versions).

**Comment by LSTANCZYK** [comment]
Thank you
