### ISSUE TITLE
Can you make it UAP compatible?

### ISSUE THREAD

**Issue by DerKnerd** [Pathoschild/FluentJira#3]
I would like to use the library in Windows 10 UAP, but it is not compatible, could you create a UAP compatible version?

**Comment by Pathoschild** [comment]
Hi @DerKnerd,

I haven't looked into targeting the UAP yet. Feel free to  contribute a pull request if you're already familiar with it. Otherwise I'll keep this open for future development. :)

**Comment by Pathoschild** [comment]
Done! Deployed to NuGet in 0.0.3-alpha.

@DerKnerd the client should be compatible with Windows 10 UAP now, though I don't have a UAP project to test it. If you still need this, let me know how it goes. :)
